### ISSUE TITLE
frontend: check toggling bug

### ISSUE THREAD

**Issue by minty99** [swsnu/swpp18-team8#38]
1. A과목 검색하고 추가
2. B과목 검색하고 추가
3. A과목 다시 검색
4. 제거를 누르면 중복으로 추가되고, 다시 누르면 그 항목이 삭제됨

intended behavior: 4번에서 제거를 누르면 원래 있던 A과목이 삭제되어야 함

**Comment by MountGuy** [comment]
수정되었음. develop branch의 커밋 로그 참조 바람.
