### ISSUE TITLE
코드리뷰(Team 11)

### ISSUE THREAD

**Issue by kyunggeun-lee** [swsnu/swpp18-team8#50]
## Team 8

[https://github.com/swsnu/swpp18-team8/blob/Sprint-4/backend/noticetracker/views.py#L56](https://github.com/swsnu/swpp18-team8/blob/Sprint-4/backend/noticetracker/views.py#L56)

- userInst라는 의미를 이름으로 유추하기 힘듬.

[https://github.com/swsnu/swpp18-team8/blob/Sprint-4/backend/noticetracker/crawl.py#L57](https://github.com/swsnu/swpp18-team8/blob/Sprint-4/backend/noticetracker/crawl.py#L57)

Method가 너무 큼: Method extract 필요

example:

    ...
    def parse_record( ):
        ...
    
    # method extract.
    def parse(html_text):
        courseDataResult = []
    
        idx = 0
        check = 0
        timeCount = 0
        bsObject = BeautifulSoup(html_text, "html.parser")
        tbodyList = bsObject.find('html').extract()
        rawCourse = bsObject
        course = rawCourse.find_all('td')
    
        courseData = None
        while idx < len(course):
            c = course[idx]
            if 'input name="check"' in str(c) or idx == 0:
                if idx == 0:
                    idx = -1
                name = course[idx + 8].text
                lectureCode = course[idx + 6].text
                profName = course[idx + 13].text
                classNumber = course[idx + 7].text
                courseData = Course(
                    name=name,
                    lectureCode=lectureCode,
                    profName=profName,
                    classNumber=classNumber
                )
                # print(name, lectureCode, profName, classNumber)
                courseData.save()
    
                # Process LectureTime.
                lectureTimes = []
                timeIndex = idx + 10
                lectureTimes += [lectureTimeDataProcess(courseData, course[timeIndex].text)]
    
                timeIndex += 8
                while timeIndex < len(course) and course[timeIndex].has_attr('class') and course[timeIndex]['class'][0] == 'blue_st':
                    lectureTimes += [lectureTimeDataProcess(courseData, course[timeIndex].text)]
                    timeIndex += 3
    
                courseDataResult += [(name, lectureCode,
                                      profName, classNumber, lectureTimes)]
            if idx == -1:
                idx = 0
            idx += 1
        return courseDataResult
    
    def crawler(i):
        url_front = "http://sugang.snu.ac.kr/sugang/cc/cc100.action?workType=S&pageNo="
        url_back = "&srchCond=1&srchOpenSchyy=2018&srchOpenShtm=U000200002U000300001"
        html = requests.get(url_front + str(i) + url_back)
        if html.status_code == 200:
            return parse(html.text)
        else:
    			....
    ...

[https://github.com/swsnu/swpp18-team8/blob/Sprint-4/backend/noticetracker/crawl.py#L25](https://github.com/swsnu/swpp18-team8/blob/Sprint-4/backend/noticetracker/crawl.py#L25)

    def lectureTimeDataProcess(courseData, time):

- None type이 리턴 or IndexError가 raise될 수 있음!
    - try: except IndexError로 안쪽에 감싸주기
    - crawl()에서 lectureTimeDataProcess를 가져다 쓸떄 None이 리턴되는지 체크하기.
- argument 이름 time: string을 나타내는 이름으로 부적절. python 내에서 다른 의미로 많이 쓰임 (모듈도 있음)

[https://github.com/swsnu/swpp18-team8/blob/Sprint-4/frontend/src/app/stub.ts#L68](https://github.com/swsnu/swpp18-team8/blob/Sprint-4/frontend/src/app/stub.ts#L68)

    searchByCode: function(courseCode: string) {

    searchByCode(courseCode: string) {

으로 대체 가능.

[https://github.com/swsnu/swpp18-team8/blob/Sprint-4/frontend/src/app/submit-time-table/submit-time-table.component.ts](https://github.com/swsnu/swpp18-team8/blob/Sprint-4/frontend/src/app/submit-time-table/submit-time-table.component.ts)

    class SubmitTimeTableComponent {
      ...
      searchedCourses: Course[] = [];
      // selectedCourse -> selectedCourses (복수형을 써서 항상 array임을 이름만 봐도 알 수 있도록 바꾸기)
      selectedCourses: Course[] = [];
      // id를 key로 하는 mapping table로 만들기. html template구현이 쉬워짐 (index 불필요)
      searchedCoursesSelected: any = {};
      ...
    
      searchByName() {
        this.courseService.searchByName(this.nameTerm).subscribe(list => {
          this.searchedCourses = list;
          this.searchedCoursesSelected = {};
          for (let item of list) {
    				// Array.some 메서드 활용
            this.searchedCoursesSelected[item.id] = this.selectedCourses.some(course => course.id === item.id);
          }
        });
      }
    
    
    }
    
    
    
    //  submit-time-table.component.html
    
    <li class="list-group-item" *ngFor="let course of searchedCourse">
      <input
        type="checkbox"
        [(ngModel)]="searchedCourseSelected[course.id]"
        (change)="this.toggleOnSearchedList(course)"/>
      {{ course.name }} {{ course.code }}
      </li>
    </li>

**Comment by minty99** [comment]
function keyword 삭제했음.
